[project]
name = "handwritten-equation-solver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "streamlit>=1.53.1",
    "streamlit-drawable-canvas>=0.9.3",
    "uvicorn>=0.40.0",
]
